name: PnW API Fetch

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight (UTC)

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install pnwkit dotenv

      - name: Fetch nation data
        run: |
          node fetchData.js

      - name: Commit the updated data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./nationData.json
          git commit -m "Update nation data"
          git push